# SNIK-Toolset, Maintainer: Konrad Höffner <konrad.hoeffner@imise.uni-leipzig.de>, originally Sebastian Stäubert  <sebastian.staeubert@imise.uni-leipzig.de>

services:

  virtuoso:
    image: openlink/virtuoso-opensource-7
    environment:
      - DBA_PASSWORD=${DBA_PASSWORD}
      - VIRT_DATABASE_ERRORLOGLEVEL=3
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=10000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=6000
      - VIRT_HTTPSERVER_SERVERPORT=8890
      - VIRT_SPARQL_DEFAULTGRAPH=http://www.snik.eu/ontology
      - VIRT_SPARQL_RESULTSETMAXROWS=50000
      - VIRT_SPARQL_MAXQUERYCOSTESTIMATIONTIME=400
      - VIRT_SPARQL_MAXQUERYEXECUTIONTIME=120
      - VIRT_SPARQL_DEFAULTQUERY=select distinct * {?s a meta:Role.} LIMIT 100
      - VIRT_PLUGINS_-=-
    volumes:
      - ./ontology:/database/data
      - ./virtuoso:/opt/virtuoso-opensource/initdb.d
      #- virtuoso-data:/database/data
    ports:
      - "127.0.0.1:8080:8890"
      - "127.0.0.1:1111:1111"
    restart: unless-stopped

  rickview:
    build: ./rickview
    environment:
      - RICKVIEW_KB_FILE=/ontology/bb.ttl
      - RICKVIEW_BASE_PATH=/ontology
      - RICKVIEW_TITLE=SNIK
      - RICKVIEW_SUBTITLE=Semantic Network of Information Management in Hospitals
      - RICKVIEW_EXAMPLES=/meta/Top /meta/EntityType /meta/Function meta/Role bb/ChiefExecutiveOfficer ob/ChiefInformationOfficer
      - RICKVIEW_HOMEPAGE=https://www.snik.eu
      - RICKVIEW_ENDPOINT=https://www.snik.eu/sparql
      - RICKVIEW_GITHUB=https://github.com/snikproject/ontology
    volumes:
      - ./ontology:/ontology
    profiles: ["rickview"]
    ports:
      - "127.0.0.1:8889:8080"
    depends_on:
      - virtuoso
    restart: unless-stopped

  graph:
    build:
      context: ./graph
      args:
        # client side, so we use the port on the local machine
        - SPARQL_ENDPOINT=http://127.0.0.1:8080/sparql
    profiles: ["graph"]
    ports:
      - "127.0.0.1:8043:8043"
    depends_on:
      - virtuoso

  proxy:
    image: caddy:2-alpine
    profiles: ["proxy"]
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "127.0.0.1:80:80"

#volumes:
#  virtuoso-data:
