# Autor: Sebastian Stäubert <sebastian.staeubert@imise.uni-leipzig.de>

version: '2'

services:

# Virtuoso:
#   Access via http://<hostname>:8080
#   Access vio iSQL://localhost:1111
  virtuoso:
    image: openlink/virtuoso-opensource-7:7
    #image: tenforce/virtuoso:1.2.0-virtuoso7.2.4
    #image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
    #image: tenforce/virtuoso:1.3.2-virtuoso7.2.4
    #image: tenforce/virtuoso:virtuoso7.2.5
    environment:
      DBA_PASSWORD: 'dba'
      SPARQL_UPDATE: 'true'
      #DEFAULT_GRAPH: 'http://www.snik.eu/ontology'
      VIRT_DefaultGraph: 'http://www.snik.eu/ontology'
    volumes:
      - virtuoso-lib:/usr/local/virtuoso-opensource/lib
      - virtuoso-data:/data
      - virtuoso-database:/database
    ports:
      - "127.0.0.1:8080:8890"
      - "127.0.0.1:1111:1111"
    restart: unless-stopped

# OntoWiki/phpserver
# Achtung: es muss noch manuell ein Link von /var/www/html -> ontowiki gesetzt werden!
#  phpserver:
#    image: aksw/php-5.6-fpm-odbc-virtuoso
#    #build: ./phpserver
#    environment:
#      #DBA_PASSWORD: 'dba'
#      SPARQL_UPDATE: "true"
#    volumes_from:
#      - ontowiki 
#      - virtuoso
#    volumes:
#      - ./config.ini:/var/www/html/config.ini
#      #  - virtuoso-data:/usr/local/virtuoso-opensource/lib
#    links:
#      - virtuoso
#    restart: unless-stopped

# OntoWiki/nginx
#   Access via http://<hostname>:8085/ontowiki
#  nginx:
#    #image: aksw/nginx-ontowiki
#    build: ./nginx
#    volumes_from:
#      #- ontowiki
#      - phpserver
#    #volumes:
#    #  - ./nginx.conf:/etc/nginx/nginx.conf
#    #  - nmdr_virtuoso-data:/usr/local/virtuoso-opensource/lib
#    links:
#      - phpserver
#   ports:
#      #- "127.0.0.1:8085:80"
#      - "8085:80"
#    restart: unless-stopped

# OntoWiki/ontowiki
#  ontowiki:
#    #image: aksw/ontowiki
#    build: ./ontowiki
#    #environment:
#      #DBA_PASSWORD: dba
#      #SPARQL_UPDATE: "true" 
#    volumes:
#    #  - nmdr_virtuoso-data:/usr/local/virtuoso-opensource/lib
#      - /var/www/html
#    links:
#      - virtuoso
#    restart: unless-stopped

# LodView
#   Access via http://<hostname>:8889
  lodview:
    build: ./lodview
    ports:
      - "127.0.0.1:8889:8080"
    links:
      - virtuoso
    restart: unless-stopped

# TripleCheckMate
#   Access via http://<hostname>:8888
  triplecheckmate:
    build: ./TripleCheckMate
    ports:
      - "127.0.0.1:8888:8080"
    links:
      - virtuoso
    restart: unless-stopped

volumes:
  virtuoso-lib:
  virtuoso-data:
  virtuoso-database:
