[namespaces]
bb = "http://www.snik.eu/ontology/bb/"
ob = "http://www.snik.eu/ontology/ob/"
meta = "http://www.snik.eu/ontology/meta/"
he = "http://www.snik.eu/ontology/he/"
it = "http://www.snik.eu/ontology/it/"
ciox = "http://www.snik.eu/ontology/ciox/"
purl = "http://purl.org/vocab/vann/"
rdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
rdfs = "http://www.w3.org/2000/01/rdf-schema#"
owl = "http://www.w3.org/2002/07/owl#"
skos = "http://www.w3.org/2004/02/skos/core#"
sh = "http://www.w3.org/ns/shacl#"
ov = "http://open.vocab.org/terms/"
foaf = "http://xmlns.com/foaf/0.1/"
yago = "http://yago-knowledge.org/resource/"
dbo = "http://dbpedia.org/ontology/"
dbp = "http://dbpedia.org/property/"
dc = "http://purl.org/dc/elements/1.1/"
xsd = "http://www.w3.org/2001/XMLSchema#"
schema = "http://schema.org/"
org = "http://www.w3.org/ns/org#"
dct = "http://purl.org/dc/terms/"
